### ISSUE TITLE
How to post json data to a plugin

### ISSUE THREAD

**Issue by cpjolly** [techjoomla/com_api-plugins#51]
I need to read json data from the post body but all the example plugins seem to just read data from the query string.

I could use  file_get_contents('php://input') inside my post method but I just wondered if there is a better way ?

Do you have example plugins that read json data from the post body ?

**Comment by coolbung** [comment]
I dont have examples, but if you're posting raw json, you can use
`$input->json->get('field_value')` to retrieve the value of a particular
variable.

**Comment by cpjolly** [comment]
Thanks yes, I see that now
