### ISSUE TITLE
Errors when installing plugins.

### ISSUE THREAD

**Issue by devlinpadayachee** [techjoomla/com_api-plugins#79]
I receive an error whenever i try to install a plugin, if i discover the plugin and install, this occurs.

php is 5.6+

![image](https://user-images.githubusercontent.com/4748730/34911737-008a0398-f8d9-11e7-8fac-8a6f5ba61047.png)

**Comment by parthlawate** [comment]
What version of Joomla are you using ?

**Comment by thite-amol** [comment]
This issue is being closed as inactive due to the date of the last activity on it.
