### ISSUE TITLE
Errors when installing plugins 

### ISSUE THREAD

**Issue by jaspreetsinghmadan** [techjoomla/com_api-plugins#93]
Hi,
I am getting error-> Call to a member function children() on null, while installing plugins from this repository.

Joomla version - 3.9
php version - 7.0.10

com_api was successfully installed, but all other plugins are throwing this error.

**Comment by manojLondhe** [comment]
Hello,

Which com_api version you are trying to install?
Where did you get it from?

**Comment by jaspreetsinghmadan** [comment]
Hi,
I have installed 2.4.0 version of com_api from
https://techjoomla.com/index.php?option=com_ars&view=Releases&category_id=23&Itemid=390
I am able to successfully install com_api.
Problem is, I am not getting much documentation for com_api. Specially kind
of getting started documentation. That talks about how to integrate com_api
and expose simple API from scratch. May be i am missing some important
links.

And While searching I found com_api_plugin
https://github.com/techjoomla/com_api-plugins. It seems like sample plugins
which i can install and expose few APIs.
But installation is failing for these plugins. I have tried user plugin.

Your inputs are much appreciated.

Thanks,
Jaspreet

**Comment by manojLondhe** [comment]
Here are links to

- com_api https://github.com/techjoomla/com_api
- com_api docs http://docs.techjoomla.com/joomla-rest-api/com-api-introduction.html
- com_api creating own plugin http://docs.techjoomla.com/joomla-rest-api/com-api-plugin-development.html
- User plugin has been moved here https://github.com/techjoomla/plg_api_users

I hope this helps.

**Comment by jaspreetsinghmadan** [comment]
Thanks for quick response.
Much appreciated.

I will go through these links, hopefully i should be able to make some
progress.
In case required, i will get back to you.

**Comment by manojLondhe** [comment]
Sure, you are welcome!

**Comment by manojLondhe** [comment]
Closing...
